### ISSUE TITLE
Error Running Ambar

### ISSUE THREAD

**Issue by dkhd** [RD17/ambar#110]
Hi all,

I successfully installed the Ambar through this guide: https://blog.ambar.cloud/ambar-installation-step-by-step-guide-2/ (I remove the line that's related to `/etc/rc.local` because it's not found in my system; source: [this issue](https://github.com/RD17/ambar/issues/94)).

But somehow I can't run it after the installation. Here's the error log:

```
______           ____     ______  ____
/\  _  \  /'\_/`\/\  _`\  /\  _  \/\  _`\
\ \ \L\ \/\      \ \ \L\ \ \ \L\ \ \ \L\ \
 \ \  __ \ \ \__\ \ \  _ <'\ \  __ \ \ ,  /
  \ \ \/\ \ \ \_/\ \ \ \L\ \ \ \/\ \ \ \ \
   \ \_\ \_\ \_\ \_\ \____/ \ \_\ \_\ \_\ \_\
    \/_/\/_/\/_/ \/_/\/___/   \/_/\/_/\/_/\/ /



Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a9
vm.max_map_count = 262144
net.ipv4.ip_local_port_range = 15000 61000
net.ipv4.tcp_fin_timeout = 30
net.core.somaxconn = 1024
net.core.netdev_max_backlog = 2000
net.ipv4.tcp_max_syn_backlog = 2048
vm.overcommit_memory = 1
ambar_db_1 is up-to-date
ambar_es_1 is up-to-date
ambar_redis_1 is up-to-date
ambar_rabbit_1 is up-to-date
ambar_webapi_1 is up-to-date

ERROR: for frontend  Container "4149a77903a9" is unhealthy.
ERROR: Encountered errors while bringing up the project.
Traceback (most recent call last):
  File "./ambar.py", line 264, in <module>
    start(configuration)
  File "./ambar.py", line 209, in start
    runShellCommandStrict('docker-compose -f {0}/docker-compose.yml -p ambar up -d'.format(PATH))
  File "./ambar.py", line 64, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker-compose -f /this/is/a/path/to/my/docker-compose.yml -p ambar up -d' returned non-zero exit status 1
```

And here's my system:
```
$ uname -a
Linux vps150910 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.2 (stretch)
Release:        9.2
Codename:       stretch

$ docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:54 2017
  OS/Arch:      linux/amd64
  Experimental: false

$ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9
```

What should I do to fix this error?

**Comment by dkhd** [comment]
I also change the default MongoDB port from `27017` to `27018` in file `docker-compose.yml` (everything that matched `27017` are changed to `27018`) because this port is already being used by another existing MongoDB service in my system.

**Comment by dkhd** [comment]
Solved! 

I reconfigure the existing MongoDB and revert the `docker-compose.yml` back to the default.

Have a nice day!

**Comment by sochix** [comment]
@dkhd nice!
