### ISSUE TITLE
Debian 9 installation error

### ISSUE THREAD

**Issue by albiz** [RD17/ambar#122]
During installation I get this error:

./ambar.py install 
..
..
..
Pulling proxy (ambar/ambar-proxy:latest)...
latest: Pulling from ambar/ambar-proxy
Digest: sha256:1827e1cce780518c09398ed1f866ef77eda1f46656e2dd2501c97d47107cc6bb
Status: Image is up to date for ambar/ambar-proxy:latest
Traceback (most recent call last):
  File "./ambar.py", line 283, in <module>
    install(configuration)
  File "./ambar.py", line 203, in install
    setOsConstants()
  File "./ambar.py", line 113, in setOsConstants
    with open('/etc/rc.local', 'r') as rcLocalConfigFile:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/rc.local'

Please let me know how to solve this. Thanks in advance,

Albiz

*  Following instructions from https://ambar.cloud/ Running on debian 9 stable

**Comment by albiz** [comment]
answered here https://github.com/RD17/ambar/issues/94. Please close
