### ISSUE TITLE
connection errors to http://serviceapi:8080/api/logs

### ISSUE THREAD

**Issue by chesty** [RD17/ambar#167]
This is amazing software for such a small team, which I think is 1. well done.

Should the apiURL in config.js https://github.com/RD17/ambar/blob/master/LocalCrawler/src/config.js  for  the crawlers be http://webapi:8080 ?

This is from a crawler

```
{ RequestError: Error: connect ECONNREFUSED 172.22.0.6:8080
    at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/node_modules/request/request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  message: 'Error: connect ECONNREFUSED 172.22.0.6:8080',
  cause: 
   { Error: connect ECONNREFUSED 172.22.0.6:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '172.22.0.6',
     port: 8080 },
  error: 
   { Error: connect ECONNREFUSED 172.22.0.6:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '172.22.0.6',
     port: 8080 },
  options: 
   { uri: 'http://serviceapi:8080/api/logs',
     method: 'POST',
     body: '{"source_id":"group-drive","type":"info","message":"Creating fork for the file-watcher process","created_datetime":"2018-06-20 15:00:03.148"}',
     headers: { 'Content-Type': 'application/json' },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
```

**Comment by sochix** [comment]
Yep, it should.

**Comment by ratio91** [comment]
+1 
I also have this problem. Can you please fix this and upload a new build on docker hub? thanks!

**Comment by musical10441** [comment]
+1
