### ISSUE TITLE
All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

### ISSUE THREAD

**Issue by thebetterjort** [RD17/ambar#18]
```
mkdir ambar
cd ambar/
```

`wget -O ambar.py https://static.ambar.cloud/ambar.py && chmod +x ./ambar.py
`
`sudo ./ambar.py install`

ERROR: In file '/home/username/ambar/docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
Traceback (most recent call last):
  File "./ambar.py", line 237, in <module>
    install(configuration)
  File "./ambar.py", line 180, in install
    pullImages(configuration)
  File "./ambar.py", line 100, in pullImages
    runShellCommandStrict("docker-compose -f {0}/docker-compose.yml pull".format(PATH))
  File "./ambar.py", line 45, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker-compose -f /home/username/ambar/docker-compose.yml pull' returned non-zero exit status 1

Not sure what I have done to deserve this treatment.

**Comment by thebetterjort** [comment]
This appears to be related more with docker than this package.

Steps to solve:
apt remove docker docker-engine
install docker-ce or docker-ee 
which is the proper way to install
I had an old script, apt install docker.io that created this issue.
