### ISSUE TITLE
"Oops... sometyhing get wrong, reload the page" index_not_found_exception

### ISSUE THREAD

**Issue by RogersNelson** [RD17/ambar#188]
Hi,

As Ambar seems to do exactly what I need, I wanted to test it on my laptop fir a first test.
Unfortunately, when I go on http://localhost/, I see the message "Oops... sometyhing get wrong, reload the page"

The browser console shows :
```
"Response 500 Internal Server Error at http://192.168.128.70:8080/api/tags"  app.2b176778cc20d3b604ca.js:2:22388
loadTags Response { type: "cors", url: "http://192.168.128.70:8080/api/tags", redirected: false, status: 500, ok: false, statusText: "Internal Server Error", headers: Headers, bodyUsed: false }  0.searchPage.65e8b6c4cb7c23cb7b9e.js:33:20778
```

The page http://192.168.128.70:8080/api/tags shows: 
```
{"message":"[index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"ambar_file_data\" & index_uuid=\"_na_\" & index=\"ambar_file_data\" }\n
Error: [index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"ambar_file_data\" & index_uuid=\"_na_\" & index=\"ambar_file_data\" }\n
at respond (/node_modules/elasticsearch/src/lib/transport.js:289:15)\n
at checkRespForFailure (/node_modules/elasticsearch/src/lib/transport.js:248:7)\n
at HttpConnector.<anonymous> (/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)\n
at IncomingMessage.wrapper (/node_modules/lodash/lodash.js:4994:19)\n    at emitNone (events.js:111:20)\n
at IncomingMessage.emit (events.js:208:7)\n
at endReadableNT (_stream_readable.js:1064:12)\n
at _combinedTickCallback (internal/process/next_tick.js:138:11)\n
at process._tickCallback (internal/process/next_tick.js:180:9)"}
```

And the docker-compose.yml contains : 
```version: "2.1"
networks:
  internal_network:
services:      
  db:
    restart: always
    networks:
      - internal_network
    image: ambar/ambar-mongodb:latest
    environment:
      - cacheSizeGB=2
    volumes:
      - /home/myname/opt/ambar/dataPath/db:/data/db
    expose:
      - "27017"   
  es:
    restart: always
    networks:
      - internal_network
    image: ambar/ambar-es:latest
    expose:
      - "9200" 
    environment:
      - cluster.name=ambar-es
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1  
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /home/myname/opt/ambar/dataPath/es:/usr/share/elasticsearch/data
  rabbit:
    restart: always
    networks:
      - internal_network
    image: ambar/ambar-rabbit:latest
    hostname: rabbit
    expose:
      - "15672"
      - "5672"   
    volumes:
      - /home/myname/opt/ambar/dataPath/rabbit:/var/lib/rabbitmq
  redis:
    restart: always
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - internal_network
    image: ambar/ambar-redis:latest
    expose:
      - "6379" 
  serviceapi:
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      es:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    image: ambar/ambar-serviceapi:latest
    expose:
      - "8081"  
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=ambar_fr   
  webapi:
    depends_on:
      serviceapi:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    image: ambar/ambar-webapi:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:      
      - analyticsToken=cda4b0bb11a1f32aed7564b08c455992
      - uiLang=en
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - serviceApiUrl=http://serviceapi:8081
      - rabbitHost=amqp://rabbit    
  frontend:
    depends_on:
      webapi:
        condition: service_healthy
    image: ambar/ambar-frontend:latest
    restart: always
    networks:
      - internal_network
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - api=http://192.168.128.70:8080  
  pipeline0:
    depends_on: 
      serviceapi: 
        condition: service_healthy                            
    image: ambar/ambar-pipeline:latest
    restart: always
    networks:
      - internal_network  
    environment:                
      - id=0
      - api_url=http://serviceapi:8081
      - rabbit_host=amqp://rabbit
  tests:
    depends_on: 
      serviceapi: 
        condition: service_healthy 
    image: ambar/ambar-local-crawler
    restart: always
    networks:
      - internal_network
    expose:
      - "8082"
    environment:      
      - name=${crawlerName}
    volumes:
      - /home/myname/opt/ambar/documents:/usr/data
  ```

Can someone help me?
Cheers,
Rogers.

**Comment by RogersNelson** [comment]
And in the log, I see this for all files :
```
2018-08-31 07:56:55.476: [pipeline] [error] [0] error checking meta existance for ///0001.docx 400 None
2018-08-31 07:56:55.498: [pipeline] [verbose] [0] add task received for ///0001.pptx
2018-08-31 07:56:55.511: [pipeline] [error] [0] error checking meta existance for ///0001.pptx 400 None
2018-08-31 07:56:55.531: [pipeline] [verbose] [0] add task received for ///0002.docx
2018-08-31 07:56:55.539: [pipeline] [error] [0] error checking meta existance for ///0002.docx 400 None
2018-08-31 07:56:55.559: [pipeline] [verbose] [0] add task received for ///0002.pptx
2018-08-31 07:56:55.569: [pipeline] [error] [0] error checking meta existance for ///0002.pptx 400 None
```

**Comment by m-hennig** [comment]
Run exactly in the same problem... (same error messages!)
Only major difference in setup: I set in docker-compose.yml  _- name=${crawlerName}_ to the name of the crawler service.

Any other debug info required?

Regards,
Markus

**Comment by sochix** [comment]
@m-hennig @RogersNelson check the logs of ambar_es, and also check that you set vm_max_map_count

**Comment by iladrero** [comment]
Same error message. Set vm.max_map_count=262144 but no success so far. Any ideas @sochix ?

`{"message":"[index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"ambar_file_data\" & index_uuid=\"_na_\" & index=\"ambar_file_data\" }\n Error: [index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"ambar_file_data\" & index_uuid=\"_na_\" & index=\"ambar_file_data\" }\n    at respond (/node_modules/elasticsearch/src/lib/transport.js:289:15)\n    at checkRespForFailure (/node_modules/elasticsearch/src/lib/transport.js:248:7)\n    at HttpConnector.<anonymous> (/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)\n    at IncomingMessage.wrapper (/node_modules/lodash/lodash.js:4994:19)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"}`

**Comment by iladrero** [comment]
In case it helps from the web log:

`[webapi] [error] Cannot read property 'max_score' of undefined TypeError: Cannot read property 'max_score' of undefined at /dist/services/EsProxy/EsProxy.js:310:56 at tryCallOne (/node_modules/promise/lib/core.js:37:12) at /node_modules/promise/lib/core.js:123:15 at flush (/node_modules/asap/raw.js:50:29) at _combinedTickCallback (internal/process/next_tick.js:131:7) at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by iladrero** [comment]
hi all, anybody sorted out this error yet? @RogersNelson  @m-hennig @sochix

**Comment by dschutterop** [comment]
~Chipping in with a +1 on this issue, getting the exact same error after a plain vanilla spin-up with docker-compose...~

Yeah, about that +1... it turns out that overlooking the language setting in the docker-compose file doesn't really help, going through the file with a fine toothed comb helped me out there...

**Comment by isido993** [comment]
Hello everyone,

Try removing everything from your ES storage folder, it's /home/myname/opt/ambar/dataPath/es for @RogersNelson. Stop Ambar, clear the folder and then start it again.

Also, could you share the business issue you're solving/trying to solve with Ambar with me? It'll help us develop it into a better product. Thanks.
