### ISSUE TITLE
ERROR: In file 'docker-compose.yml' service 'version' doesn't have any configuration options

### ISSUE THREAD

**Issue by repercussion** [RD17/ambar#2]
Trying to follow the blog post's instructions. Failed here:

```
ERROR: In file '/home/guy/.ambar/docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
Traceback (most recent call last):
  File "./ambar.py", line 224, in <module>
    install(configuration)
  File "./ambar.py", line 167, in install
    pullImages(configuration)
  File "./ambar.py", line 100, in pullImages
    runShellCommandStrict("docker-compose -f {0}/docker-compose.yml pull".format(PATH))
  File "./ambar.py", line 45, in runShellCommandStrict
    subprocess.check_call(command, shell = True)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker-compose -f /home/guy/.ambar/docker-compose.yml pull' returned non-zero exit status 1
```

**Comment by isido993** [comment]
What version of `docker-compose` are you using? You can view it by running `docker-compose --version`. Please provide us with this info, it seems like you have an old version of `docker-compose`.
Thnx.

**Comment by sochix** [comment]
@repercussion any news?

**Comment by repercussion** [comment]
Let me boot this sucker up...

docker-compose version 1.5.2

I'll get that up to date and report back
