### ISSUE TITLE
serviceapi  Container "..." is unhealthy. (Solution in #189 doesn't work)

### ISSUE THREAD

**Issue by asittampalam** [RD17/ambar#251]
Hey guys. First of all thanks for your great work!
I face the same issue  as in #189 :
```
docker-compose up

Starting ambar_db_1     ... done
Starting ambar_rabbit_1 ... done
Starting ambar_es_1     ... done
Starting ambar_redis_1  ... done

ERROR: for serviceapi  Container "5b4a212023f1" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

I'm on Mac OSX though (dev system). But even using
```
screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
```
to set
```
sysctl -w vm.max_map_count=262144 
sysctl -w net.ipv4.ip_local_port_range="15000 61000" 
sysctl -w net.ipv4.tcp_fin_timeout=30 
sysctl -w net.core.somaxconn=1024 
sysctl -w net.core.netdev_max_backlog=2000 
sysctl -w net.ipv4.tcp_max_syn_backlog=2048 
sysctl -w vm.overcommit_memory=1
```
doesn't solve the issue for me. Any hints? Thanks.

**Comment by asittampalam** [comment]
`docker logs` output:
```
Elasticsearch WARNING: 2019-08-09T21:56:55Z
  Unable to revive connection: http://es:9200/

Elasticsearch WARNING: 2019-08-09T21:56:55Z
  No living connections

Catastrophic failure! Error: No Living connections
[2019-08-09T21:57:56.777Z] SLAO api key must be specified
Elasticsearch ERROR: 2019-08-09T21:57:56Z
  Error: Request error, retrying
  PUT http://es:9200/ambar_log_record_data => getaddrinfo ENOTFOUND es es:9200
      at Log.error (/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/node_modules/elasticsearch/src/lib/transport.js:240:18)
      at HttpConnector.<anonymous> (/node_modules/elasticsearch/src/lib/connectors/http.js:162:7)
      at ClientRequest.wrapper (/node_modules/lodash/lodash.js:4929:19)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at Socket.socketErrorListener (_http_client.js:387:9)
      at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

Elasticsearch WARNING: 2019-08-09T21:57:56Z
  Unable to revive connection: http://es:9200/

Elasticsearch WARNING: 2019-08-09T21:57:56Z
  No living connections

Catastrophic failure! Error: No Living connections
```
(A lot of repetitions of this block)

**Comment by asittampalam** [comment]
Update:

Changing the following in the docker-compose file seems to "solve" the issue: `ES_JAVA_OPTS=-Xmx256m -Xms256m`. But this is a hacky solution, so I'm leaving the issue open. Could this be a Mac related issue?
