### ISSUE TITLE
Ooops! Something went wrong...

### ISSUE THREAD

**Issue by olislaeda** [RD17/ambar#274]
Доброго времени суток. Ошибка 
![image](https://user-images.githubusercontent.com/16779109/70542724-4709b500-1b7a-11ea-942f-f035fa69f061.png)

yallz@Ambar:~/ambar$ sudo docker container logs 9ddd9b2fa011
[info] API runs on master thread
[info] Creating fork for the file-watcher process
Started API on :::8082
{ RequestError: Error: connect ECONNREFUSED 172.18.0.6:8080
    at new RequestError (/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  message: 'Error: connect ECONNREFUSED 172.18.0.6:8080',
  cause:
   { Error: connect ECONNREFUSED 172.18.0.6:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '172.18.0.6',
     port: 8080 },
  error:
   { Error: connect ECONNREFUSED 172.18.0.6:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '172.18.0.6',
     port: 8080 },
  options:
   { uri: 'http://serviceapi:8080/api/logs',
     method: 'POST',
     body: '{"source_id":"mysource","type":"info","message":"API runs on master thread","created_datetime":"2019-12-10 14:38:08.515"}',
     headers: { 'Content-Type': 'application/json' },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }

yallz@Ambar:~/ambar$ sudo docker inspect c04e382a7512 | grep "IPAddress" &&  sudo docker inspect c0e382a7512 | grep "Image"
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.18.0.6",
        "Image": "sha256:bd589708ad328832e42b1d577a027b8d2dcb3eb1dcde5acaf5f7e242d689a0bc",
            "Image": "ambar_serviceapi",

docker-compose.yml:

version: "2.1"
networks:
  internal_network:
services:    
  db:
    restart: always
    networks:
      - internal_network
    build: ./MongoDB
    environment:
      - cacheSizeGB=2
    volumes:
      - /opt/ambar/db:/data/db
    expose:
      - "27017"
  es:
    restart: always
    networks:
      - internal_network
    build: ./ElasticSearch
    expose:
      - "9200"
    environment:
      - cluster.name=ambar-es
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/ambar/es:/usr/share/elasticsearch/data
  rabbit:
    restart: always
    networks:
      - internal_network
    build: ./Rabbit
    hostname: rabbit
    expose:
      - "15672"
      - "5672"
    volumes:
      - /opt/ambar/rabbit:/var/lib/rabbitmq
  redis:
    restart: always
    sysctls:
      - net.core.somaxconn=1024
    networks:
      - internal_network
    build: ./Redis
    expose:
      - "6379"
  serviceapi:
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      es:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    build: ./ServiceApi
    expose:
      - "8081"  
    environment:            
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - rabbitHost=amqp://rabbit
      - langAnalyzer=${langAnalyzer}  
      - SLAO_HOSTNAME=ambar 
      - SLAO_API_KEY=
  webapi:
    depends_on:
      serviceapi:
        condition: service_healthy
    restart: always
    networks:
      - internal_network
    build: ./WebApi
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:            
      - uiLang=en
      - mongoDbUrl=mongodb://db:27017/ambar_data
      - elasticSearchUrl=http://es:9200
      - redisHost=redis
      - redisPort=6379
      - serviceApiUrl=http://serviceapi:8081
      - rabbitHost=amqp://rabbit  
      - SLAO_HOSTNAME=ambar
      - SLAO_API_KEY=
  pipeline0:
    depends_on:
      serviceapi:
        condition: service_healthy
    build: ./Pipeline
    restart: always
    networks:
      - internal_network
    environment:
      - id=0
      - api_url=http://serviceapi:8081
      - rabbit_host=amqp://rabbit
      - ocrPdfMaxPageCount=-1
  mysource:
    depends_on:
      serviceapi:
        condition: service_healthy
    build: ./LocalCrawler
    restart: always
    networks:
      - internal_network
    expose:
      - "8082"
    environment:
      - name=mysource
    volumes:
      - /home/yallz/sources:/usr/data
  frontend:
    depends_on:
      webapi:
        condition: service_healthy
    build: ./FrontEnd
    restart: always
    networks:
      - internal_network
    ports:
      - "3000:80"
    expose:
      - "3000"
    environment:
      - api={ip}:3000

Вот такой анамнез. Файлы не загружаются. Подскажите, пожалуйста, в чём беда?

**Comment by olislaeda** [comment]
Исправил сам. 
"apiUrl": "http://serviceapi:8080" на "apiUrl": "http://serviceapi:8081" в файле LocalCrawler/src/config.js
и в фронтэнде забыл добавить ip)))
