### ISSUE TITLE
Errors while processing data

### ISSUE THREAD

**Issue by andr6** [RD17/ambar#32]
Hi,

I am seeing allot of the following errors on the pipeline for all the files being used via SMB Crawler .

2017-05-11 14:59:05.470: [error] [p0] error submiting parsed text to Api, unexpected response code //windowsxptools/g/docs/file.html 500 {"message":"Invalid non-string/buffer chunk\n TypeError: Invalid non-string/buffer chunk\n at validChunk (_stream_writable.js:186:14)\n at GridWriteStream.Writable.write (_stream_writable.js:213:12)\n at ondata (_stream_readable.js:542:20)\n at emitOne (events.js:77:13)\n at emit (events.js:169:7)\n at Readable.read (_stream_readable.js:368:10)\n at flow (_stream_readable.js:759:26)\n at resume_ (_stream_readable.js:739:3)\n at nextTickCallbackWith2Args (node.js:511:9)\n at process._tickCallback (node.js:425:17)"}

This is happening to all the files. 

Any ideas ? 

Thanks

**Comment by isido993** [comment]
Hello!

The error is not critical and won't affect search performance and experience anyhow. 
However it's a bug, and we'll fix it. Please send us the file (`file.html` - the one that generates the error) to help us investigate the issue.

Thanks

**Comment by andr6** [comment]
Hi @fpd4444 

Can't do that :) But this happening to all files now.

**Comment by isido993** [comment]
@andr6 

We made some updates, please run `sudo ./ambar.py update` and then try processing this files again.

**Comment by sochix** [comment]
@andr6 did it help?

**Comment by andr6** [comment]
It did. No more errors on html. I am seeing the same errors being applied to images file types(jpg,, png, etc)

I haven't upgrade yet to the latest version since my understanding is that it will need to start from 0.

**Comment by isido993** [comment]
@andr6 
We fixed the error you mentioned (processing images) in the latest version. Please update (you're right, it requires resetting Ambar index, but it worth it since the search is much more advance in this new version)

**Comment by andr6** [comment]
@fpd4444  If i upgrade does the data needs to be reprocessed again ?

**Comment by sochix** [comment]
@andr6 yep

**Comment by sochix** [comment]
@andr6 should I close this issue?

**Comment by andr6** [comment]
Please do
