### ISSUE TITLE
No mapping found for type [ambar_file_tag]

### ISSUE THREAD

**Issue by jenkin** [RD17/ambar#58]
I updated my ambar to v1.0 and now file processing doesn't work, using web frontend nor api.

```
[p0] error retrieving parsed file content fields //288ebfc2-e085-2eb8-613d-67440f58b1b1/db8d40c8-3e5a-34fc-90e9-2ad03fe9ab9c.pdf 500 {"message":"[query_shard_exception] [has_child] no mapping found for type [ambar_file_tag], with { index_uuid=\"RGTWV7ztQrqVz9YOS4zavg\" & index=\"ambar_file_data_d033e22ae348aeb5660fc2140aec35850c4da997\" }\n Error: [query_shard_exception] [has_child] no mapping found for type [ambar_file_tag], with { index_uuid=\"RGTWV7ztQrqVz9YOS4zavg\" & index=\"ambar_file_data_d033e22ae348aeb5660fc2140aec35850c4da997\" }\n    at respond (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:289:15)\n    at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:248:7)\n    at HttpConnector.<anonymous> (/usr/src/app/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)\n    at IncomingMessage.wrapper (/usr/src/app/node_modules/lodash/lodash.js:4994:19)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)"}
```

If I query the ES instance I can't find mapping for type `ambar_file_tag`, so the `has_child` query failes.

```
{
   "ambar_log_record_data":{
      "mappings":{
         "ambar_log_record":{
            "properties":{
               "created_datetime":{
                  "type":"date",
                  "format":"yyyy-MM-dd HH:mm:ss.SSS"
               },
               "dest_id":{
                  "type":"keyword"
               },
               "indexed_datetime":{
                  "type":"date",
                  "format":"yyyy-MM-dd HH:mm:ss.SSS"
               },
               "message":{
                  "type":"text"
               },
               "source_id":{
                  "type":"keyword"
               },
               "type":{
                  "type":"keyword"
               }
            }
         }
      }
   },
   "ambar_file_data_d033e22ae348aeb5660fc2140aec35850c4da997":{
      "mappings":{
         "ambar_file":{
            "_all":{
               "enabled":false
            },
            "_source":{
               "excludes":[
                  "content.text"
               ]
            },
            "properties":{
               "content":{
                  "properties":{
                     "author":{
                        "type":"text",
                        "analyzer":"ambar_keyword",
                        "fielddata":true
                     },
                     "indexed_datetime":{
                        "type":"date",
                        "format":"yyyy-MM-dd HH:mm:ss.SSS"
                     },
                     "language":{
                        "type":"text",
                        "analyzer":"ambar_keyword",
                        "fielddata":true
                     },
                     "length":{
                        "type":"long"
                     },
                     "processed_datetime":{
                        "type":"date",
                        "format":"yyyy-MM-dd HH:mm:ss.SSS"
                     },
                     "size":{
                        "type":"long"
                     },
                     "state":{
                        "type":"keyword"
                     },
                     "text":{
                        "type":"text",
                        "store":true,
                        "term_vector":"with_positions_offsets",
                        "analyzer":"ambar_en"
                     },
                     "thumb_available":{
                        "type":"boolean"
                     },
                     "title":{
                        "type":"text"
                     },
                     "type":{
                        "type":"text",
                        "analyzer":"ambar_keyword",
                        "fielddata":true
                     }
                  }
               },
               "meta":{
                  "type":"nested",
                  "properties":{
                     "created_datetime":{
                        "type":"date",
                        "format":"yyyy-MM-dd HH:mm:ss.SSS"
                     },
                     "extension":{
                        "type":"text",
                        "analyzer":"ambar_keyword",
                        "fielddata":true
                     },
                     "extra":{
                        "properties":{
                           "type":{
                              "type":"keyword"
                           },
                           "value":{
                              "type":"text"
                           }
                        }
                     },
                     "full_name":{
                        "type":"text",
                        "analyzer":"ambar_keyword",
                        "fielddata":true
                     },
                     "id":{
                        "type":"keyword"
                     },
                     "indexed_datetime":{
                        "type":"date",
                        "format":"yyyy-MM-dd HH:mm:ss.SSS"
                     },
                     "short_name":{
                        "type":"text",
                        "analyzer":"ambar_keyword",
                        "fielddata":true
                     },
                     "source_id":{
                        "type":"text",
                        "analyzer":"ambar_keyword",
                        "fielddata":true
                     },
                     "updated_datetime":{
                        "type":"date",
                        "format":"yyyy-MM-dd HH:mm:ss.SSS"
                     }
                  }
               },
               "sha256":{
                  "type":"keyword"
               }
            }
         }
      }
   }
}
```

I also tried to update ambar again, but without results.

**Comment by sochix** [comment]
Hi @jenkin! You need to reset your index to update Ambar and recrawl all the data.
`sudo ./ambar.py reset`

**Comment by jenkin** [comment]
Ok, I needed to run `sudo ./ambar.py uninstall` (and maybe also restart docker daemon) and reinstall everything to have a working application. Now it works, thanks.
